imports

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelBinarizer,MinMaxScaler
from keras.models import Sequential
from keras.layers import Dense,Dropout,Activation

In [ ]:
from tensorflow.keras.optimizers import SGD

data

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
student_data=pd.read_csv('/content/drive/MyDrive/student_data.csv')
student_data.shape

(555, 24)

data preparation

In [ ]:
student_data.isnull().values.any()

False

In [ ]:
student_data.head()

English Writing  ...                    Profession
0              0.0  ...                            IT
1             44.0  ...  Writing and Content Creation
2              0.0  ...                            IT
3             44.0  ...       Design and Architecture
4             11.0  ...       Design and Architecture

[5 rows x 24 columns]

In [ ]:
y=LabelBinarizer().fit_transform(student_data.Profession)

In [ ]:
y.shape

(555, 6)

In [ ]:
x=pd.DataFrame(student_data.drop('Profession',axis=1))

In [ ]:
x.shape

(555, 23)

In [ ]:
scaler=MinMaxScaler()
x=scaler.fit_transform(x)

In [ ]:
x

array([[0.  , 0.07, 0.11, ..., 0.3 , 0.44, 0.09],
       [0.44, 0.  , 0.44, ..., 0.5 , 0.  , 0.09],
       [0.  , 0.36, 0.44, ..., 0.1 , 0.33, 0.18],
       ...,
       [0.22, 0.  , 0.22, ..., 0.6 , 0.33, 0.09],
       [0.  , 0.  , 0.11, ..., 0.4 , 0.67, 0.27],
       [0.56, 0.36, 0.11, ..., 0.5 , 0.22, 0.36]])

In [ ]:
X_train,X_test,Y_train,Y_test=train_test_split(x,y,train_size=0.7,random_state=1)

In [ ]:
X_train.shape

(388, 23)

In [ ]:
Y_train.shape

(388, 6)

In [ ]:
np.savetxt("test_data.csv", X_test, delimiter=",")

training and testing

In [ ]:
model=Sequential()

model.add(Dense(64,activation='relu',input_dim=23))
model.add(Dropout(0.5))
model.add(Dense(64,activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(64,activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(6, activation='softmax'))

In [ ]:
sgd=SGD(learning_rate=0.01,decay=1e-6,momentum=0.9,nesterov=True)

In [ ]:
model.compile(loss='categorical_crossentropy',optimizer=sgd,metrics=['accuracy'])

In [ ]:
model.fit(X_train,Y_train,epochs=500,batch_size=128)

Epoch 1/500
4/4 [==============================] - 1s 8ms/step - loss: 1.7746 - accuracy: 0.2371
Epoch 2/500
4/4 [==============================] - 0s 7ms/step - loss: 1.7340 - accuracy: 0.2809
Epoch 3/500
4/4 [==============================] - 0s 5ms/step - loss: 1.6772 - accuracy: 0.2938
Epoch 4/500
4/4 [==============================] - 0s 4ms/step - loss: 1.6138 - accuracy: 0.3428
Epoch 5/500
4/4 [==============================] - 0s 5ms/step - loss: 1.5759 - accuracy: 0.3840
Epoch 6/500
4/4 [==============================] - 0s 5ms/step - loss: 1.5897 - accuracy: 0.3428
Epoch 7/500
4/4 [==============================] - 0s 4ms/step - loss: 1.5497 - accuracy: 0.3299
Epoch 8/500
4/4 [==============================] - 0s 5ms/step - loss: 1.5184 - accuracy: 0.3582
Epoch 9/500
4/4 [==============================] - 0s 6ms/step - loss: 1.5692 - accuracy: 0.3634
Epoch 10/500
4/4 [==============================] - 0s 5ms/step - loss: 1.5186 - accuracy: 0.3814
Epoch 11/500
4/4 [===========

In [ ]:
model.evaluate(X_test,Y_test,batch_size=128)

2/2 [==============================] - 0s 8ms/step - loss: 0.7796 - accuracy: 0.7904


[0.779644787311554, 0.7904191613197327]

In [ ]:
pred=model.predict(X_test[0:10], batch_size=None, verbose=0, steps=None)

In [ ]:
pred

array([[1.55962561e-03, 3.45227978e-04, 1.14202678e-01, 4.59688902e-03,
        8.55228484e-01, 2.40670629e-02],
       [5.28363846e-02, 8.19483772e-02, 5.47951698e-01, 2.07375567e-02,
        1.21642150e-01, 1.74883798e-01],
       [8.85569025e-04, 6.41861770e-05, 9.53275263e-01, 2.78953376e-05,
        1.19282994e-02, 3.38188186e-02],
       [9.38802036e-10, 1.29973059e-13, 9.99968052e-01, 2.94129175e-14,
        2.20955849e-06, 2.96426679e-05],
       [5.36018051e-02, 3.27627994e-02, 6.05177045e-01, 1.59526970e-02,
        1.52350351e-01, 1.40155360e-01],
       [8.70375156e-01, 1.33472653e-02, 6.19071648e-02, 1.92442685e-02,
        3.11500300e-02, 3.97604192e-03],
       [2.46863533e-02, 5.04007220e-01, 5.54178394e-02, 1.49484247e-01,
        1.43468544e-01, 1.22935884e-01],
       [9.64819975e-08, 2.40243717e-05, 1.04762556e-04, 2.16918765e-03,
        6.91900915e-03, 9.90782917e-01],
       [1.02161067e-02, 2.56420975e-03, 8.44693303e-01, 9.56629927e-04,
        3.82233001e-02, 

In [ ]:
X_test[14:15]

array([[0.33, 0.29, 0.56, 0.1 , 0.12, 0.  , 0.09, 0.  , 0.08, 0.33, 0.29,
        0.2 , 0.11, 0.44, 0.44, 0.4 , 0.12, 0.  , 0.18, 0.25, 0.8 , 0.22,
        0.36]])

In [ ]:
model.save('model.h5', save_format='h5')